Add Foundry To Chains Export
tmm/wagmi pull request #564
Opened 2022-06-07 21:39 UTC by carllippert

Foundry is becoming more popular. This makes it easy for all.

## Description

Make Foundry as easy as hardhat

## Additional Information

- [x] I read the [contributing docs](/tmm/wagmi/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address:

carllippert.eth

2022-06-08 01:47 UTC, jxom commented on packages/core/src/constants/chains.ts
> +  foundry: 31337
```suggestion
  foundry: 31_337
```

2022-06-08 02:21 UTC, tmm requested changes
We should export this from the tree shakable chains entrypoint in each package.

Also, should we call this Foundry Anvil?

2022-06-08 13:19 UTC, carllippert commented
Was thinking the same about Anvil naming! Someone from that team probably has an opinion but don't know them.

2022-06-10 00:44 UTC, tmm commented
Closing in favor of https://github.com/tmm/wagmi/pull/570

2022-06-10 00:44 UTC, closed without merging